# Generated by Django 4.2 on 2023-04-24 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_child1_child2_child3_delete_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child1',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_child1', to='main.parent'),
        ),
        migrations.AlterField(
            model_name='child2',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_child2', to='main.child1'),
        ),
        migrations.AlterField(
            model_name='child3',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_child3', to='main.child2'),
        ),
    ]
